version: '3'
services:
  api:
    image: dominyka/books
    build: .
    networks:
      - backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - backend
    ports:
      - "27017:27017"

networks:
  backend:
    driver: bridge
